// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

const String imageBaseUrl =
    'https://firebasestorage.googleapis.com/v0/b/helpwave-bfcb0.firebasestorage.app/o/common%2F';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvU1apdU1F2K8L0yTiNA2ME-mfw8eTV4U',
    appId: '1:576719437400:android:ce6faf4a8b78c0f02d542d',
    messagingSenderId: '576719437400',
    projectId: 'helpwave-bfcb0',
    storageBucket: 'helpwave-bfcb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjSxd9RZD6XdpAwujvbE9_mykF1t8HAwM',
    appId: '1:576719437400:ios:3fe2f9166522b09f2d542d',
    messagingSenderId: '576719437400',
    projectId: 'helpwave-bfcb0',
    storageBucket: 'helpwave-bfcb0.firebasestorage.app',
    iosBundleId: 'com.example.helpwaveMobileApp',
  );
}
